import { InterestProfile } from '../lib/useInterests';

/**
 * Interest Algorithm: Relevance Scoring
 * 
 * Logic:
 * 1. Social Signal: Followed authors get +50 points.
 * 2. Personal Interest: Each tag match adds points based on past engagement.
 * 3. Familiarity: Previous reads from author add points.
 * 4. Freshness: Viewed posts get a -500 penalty.
 */
export const calculateRelevanceScore = (
  contentId: string,
  contentTags: string[],
  contentAuthor: string,
  isFollowed: boolean,
  profile: InterestProfile
): number => {
  let score = 0;

  // 1. Social Signal
  if (isFollowed) score += 50;
  
  // 2. Personal Interest Signal
  contentTags.forEach(tag => {
    score += (profile.tags[tag] || 0) * 5;
  });

  // 3. Familiarity Signal
  score += (profile.authors[contentAuthor] || 0) * 3;

  // 4. Freshness Signal
  if (profile.viewedPostIds.includes(contentId)) {
    score -= 500;
  }

  return score;
};

/**
 * Hacker News-style Gravity-Decay Relevance score for Feed Ranking
 * 
 * Formula:
 * Relevance Score = (Base Engagement + (Author Priority Score * 0.5)) / (Age In Hours + 2) ^ Gravity
 * 
 * Parameters:
 * - Base Engagement: (Upvotes * 2) + (Comments * 5) + (Shares * 10)
 * - Author Priority Score: Metric generated by the Global Ranking Daemon / scoring rules (Articles/MicroPosts & Views)
 * - Age In Hours: Time elapsed since published
 * - Gravity: Constant (1.8 in this implementation for fresh, optimized decay)
 */
export const calculateGravityRelevanceScore = (
  post: any,
  isFollowed: boolean,
  interestScore: number
): number => {
  // Extract engagement vectors
  const upvotes = post.upvotes || post.likes || 0;
  const comments = typeof post.comments === 'number' ? post.comments : (Array.isArray(post.comments) ? post.comments.length : 0);
  const shares = post.shares || 0;

  // 1. Base Engagement
  const baseEngagement = (upvotes * 2) + (comments * 5) + (shares * 10);

  // 2. Author Priority Score (reputation map from static seeds / dynamically registered users)
  const SEED_AUTHOR_PRIORITIES: Record<string, number> = {
    'Dr. Sarah Chen': Math.round(14200 * 0.6 + 9800 * 0.4), // 12440
    'Prof. Liam Whitby': Math.round(9200 * 0.6 + 6400 * 0.4), // 8080
    'Alex Rivera': Math.round(11200 * 0.6 + 7100 * 0.4), // 9560
    'Dr. Elena Rodriguez': Math.round(10200 * 0.6 + 8200 * 0.4), // 9400
    'Marcus Thorne': Math.round(6700 * 0.6 + 4500 * 0.4), // 5820
    'dr_sarah_chen': Math.round(14200 * 0.6 + 9800 * 0.4),
    'prof_liam_whitby': Math.round(9200 * 0.6 + 6400 * 0.4),
    'alex_rivera': Math.round(11200 * 0.6 + 7100 * 0.4),
    'dr_elena_rodriguez': Math.round(10200 * 0.6 + 8200 * 0.4),
    'marcus_thorne': Math.round(6700 * 0.6 + 4500 * 0.4)
  };

  const authorName = post.author || post.authorName || '';
  const authorId = post.authorId || '';
  let authorPriority = 100; // baseline custom default value

  if (SEED_AUTHOR_PRIORITIES[authorName]) {
    authorPriority = SEED_AUTHOR_PRIORITIES[authorName];
  } else if (SEED_AUTHOR_PRIORITIES[authorId]) {
    authorPriority = SEED_AUTHOR_PRIORITIES[authorId];
  } else {
    // Dynamically retrieve user's local score if it matches the current logged in user
    try {
      const activeUserStr = localStorage.getItem('user_profile');
      if (activeUserStr) {
        const activeUser = JSON.parse(activeUserStr);
        if (activeUser.uid === authorId || activeUser.fullName === authorName || activeUser.username === authorName) {
          const ks = activeUser.stats?.knowledgeScore || 0;
          const ei = activeUser.stats?.eduImpact || 0;
          authorPriority = Math.round(ks * 0.6 + ei * 0.4);
        }
      }
    } catch {
      // Stay at baseline fallback
    }
  }

  // 3. Age In Hours calculation
  const dateVal = post.date || post.createdAt || new Date();
  const postTime = new Date(dateVal).getTime();
  const ageMs = Math.max(0, Date.now() - postTime);
  const ageInHours = ageMs / (1000 * 60 * 60);

  // 4. Gravity decay rate model constant (1.8)
  const gravity = 1.8;

  // Include personalized recommendation interest offset to numerator to retain personal relevancy
  const personalBoost = (isFollowed ? 50 : 0) + (interestScore * 0.2);

  // 5. Compute Hacker News dynamic relevance formula
  const numerator = (baseEngagement) + (authorPriority * 0.5) + personalBoost;
  const denominator = Math.pow(ageInHours + 2, gravity);

  return numerator / denominator;
};

